### PR TITLE
Add a page with general Liquid syntax guidelines

### PR DESCRIPTION
**Pull request by kmcgillivray**
Hi @benbalter, I thought this could be useful? Looking forward to feedback.

### CODE REVIEW

**Comment by benbalter** [comment]
This is great! Thanks @kmcgillivray. What do you think about vertical whitespace? I agree `assign` statements should touch the `if` statements they support, but I generally add an empty line in between unrelated `if` statements. Perhaps, adopt the Ruby idiom to group logically related clauses like you would a paragraph?

**Comment by kmcgillivray** [comment]
That makes sense to me, @benbalter—is something like this what you mean?

``` html
{% if page.title %}
  <h1>{{ page.title }}</h1>
{% endif %}

{% if page.description %}
  <p>{{ page.description }}</p>
{% endif %}
```

NOT:

``` html
{% if page.title %}
  <h1>{{ page.title }}</h1>
{% endif %}
{% if page.description %}
  <p>{{ page.description }}</p>
{% endif %}
```

Side note: do we care about how the output HTML looks? Separating the `if` statements might add lots of extra whitespace in the actual output file.

**Comment by benbalter** [comment]
> is something like this what you mean?

Yep.

> Side note: do we care about how the output HTML looks?

I'm of the opinion that humans read the liquid more often than the HTML, so we should optimize for liquid readability.

**Comment by kmcgillivray** [comment]
@benbalter Good call! Added a section about vertical whitespace and added better examples.

**Comment by benbalter** [comment]
✨ Thanks @kmcgillivray!

**Comment by kmcgillivray** [comment]
@benbalter you're welcome! I noticed the liquid tags aren't showing up on the live site. I didn't test a local build before making the pull request, my bad! Let me see if I can get a local copy running.

**Comment by benbalter** [comment]
Believe you'll need to wrap it in `{% raw %}` tags.

**Pull request merged**
